### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Появляются рамки вокруг кнопок, расположенных в хедере, при нажатии на них

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#10]
Вложение: https://monosnap.com/file/d318OwEbap8P48nxhXhBsnxMDhouyY
Ожидаемый результат: Не появляются рамки вокруг кнопок, расположенных в хедере, при нажатии на них.

**Comment by ossset** [comment]
Ошибка проявляется только в FireFox.

**Comment by Nika987** [comment]
@ossset 
так я и указала, что в браузере [Главная страница. Десктоп. Firefox]

**Comment by Nika987** [comment]
@ossset 
не исправлено

**Comment by Omeljusik** [comment]
на 10.08 на фтэсце усё ок.
