### ISSUE TITLE
[Анкета для валанцёраў, практыкантаў, стажораў. Десктоп. Firefox] Появляется рамка вокруг ссылки, расположенной в анкете для заполнения, при нажатии на нее

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#11]
Вложение: https://monosnap.com/file/gYJM78iufJaCrJLLqiZjNSaDN23kyY
Ожидаемый результат: при нажатии на ссылку нет никаких рамок.

**Comment by ossset** [comment]
Проявляется только в Firefox.

**Comment by Nika987** [comment]
@ossset 
так я и указала, что в браузере [Главная страница. Десктоп. Firefox]

**Comment by koverchik** [comment]
Эту issue не относится к главной странице это google forms https://docs.google.com/forms/d/e/1FAIpQLSf78xrCLn3zsUaXmQGNrA58puu1Mk7AK4gIFyAwVXpNU1TyAw/viewform
