### ISSUE TITLE
[Afishi] Выгляд афіш не адпавядае макетам.

### ISSUE THREAD

**Issue by Omeljusik** [falanster/devfalanster#118]
## Зараз гэта так, як на скрынах, у тым ліку
- поле img працуе у якасці малюнка для preview
- засталася галасавалка
- не выводзіцца дата-час мерапрыества у шэрам прамавугольніке ў правым ніжнем вуглу 
https://ftest.falanster.by/be/afisha/test-afishy
![image](https://user-images.githubusercontent.com/32821205/62663873-f68f0a80-b981-11e9-8fab-3a15f1960139.png)

Спасылкі для тэста: https://ftest.falanster.by/be/afisha/test-afishy-0
https://ftest.falanster.by/be/afisha/kinabunker-2018-gora-tvorca

**Comment by koverchik** [comment]
@Omeljusik я без понятия, что и кто делал на сервере и какие там шаблоны подключены.

**Comment by Omeljusik** [comment]
авдключылі тэмплэйт праз в'юс - запрацавала.
