### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Кнопка "Уваход" имеет закругление в 4рх в верхней части страницы сайта

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#12]
Вложение: https://monosnap.com/file/ZPcAq4v60Le3G2EyFLYhdr7hgJWZwB
Ожидаемый результат: согласно ТЗ все прямоугольные формы (кнопки) имеют закругления в 3рх

**Comment by ossset** [comment]
У задачи низший приоритет.

**Comment by Nika987** [comment]
@ossset 
Я не согласна. Почему ты считаешь так?

**Comment by Omeljusik** [comment]
@Nika987 Таму што гэта ніяк не перашкаджае працэ сайта, а зазор у 1px не заўважэн глазу. Тут канешне minor.
Увогуле яым больш баг перашкаджае карыстальніку нармальна працаваць з сайтам, тым вышэй яго прырытэт. Закругленне ў 4px надвор'я не створыць, але можна паправіць а апошнюю чаргу. Вось, калі б кнопка была зусім круглая, тады можна было б паставіць medium альбо major.

@Nika987 Дарэчы, чаму не растаўляеш лэйблы?

**Comment by Nika987** [comment]
@Omeljusik 
Таму што правы у мяне з'явіліся у сб. Так як задачы ужо былі паміж Олей і Сашей падзеляны, рашыла іх не пачаць, а у новых жадач лэйблы будуць стаяць)
