### ISSUE TITLE
[Унутраныя] Загалоўкі h1, h2, h3 не адпавядаюць макетам (вельмі маленькія)

### ISSUE THREAD

**Issue by Omeljusik** [falanster/devfalanster#121]
Тут памеры загалоўкаў/падзагалоўкаў, якія павінны быць https://diglabby.github.io/Falanster-site/about

**Comment by koverchik** [comment]
@Omeljusik а какие они должны быть?

**Comment by Omeljusik** [comment]
@koverchik можаш выцягваць гэту інфу з гатовай вёрсткі? мы не рабілі тз, рабята бралі макеты і версталі піксель-перфект.

**Comment by Omeljusik** [comment]
усё было добра, не выкарыстоўваем h1, пачынаем з h2
