### ISSUE TITLE
[ГП на галоўнай] Праекты не выводзяцца па вазе, як было запланавана.

### ISSUE THREAD

**Issue by Omeljusik** [falanster/devfalanster#124]
## Згодна зместу на 10.08 выводзмцца павінный
- улазіны 2.0 - 1
- афіцыйна - 2
- градка - 3
- дапамагчы - 4

Астатнія старонкі ад 0 да -20.

## Рэальна выводзицца:
- Тэст вывада статуса праекта (разпаўзаецца і няма апісання, загалоўка + эфектаў)
- Проверка 123
- Роварны куток
- Новоснлье 2.0
І кожная спасылка вядзе на https://falanster.by/be/wikification

**Comment by Omeljusik** [comment]
@ossset Вырашылі рабіць:
Гарачыя праекты: вага 1
Бягучыя: вага 2
Спыненыя: вага 3
Скончаныя: вага 4

**Comment by Omeljusik** [comment]
## Зрабіць так, каб ніякая прев'ю ці яе адсутнасць не ламала блок гарачых праектаў:

![image](https://user-images.githubusercontent.com/32821205/62837526-289db680-bc79-11e9-8487-94adfd639474.png)

**Comment by ossset** [comment]
Hot projects value = 20

**Comment by Omeljusik** [comment]
Тут ок, дзякуй!

+ вывад па вазе злева на права. Дзе больш вага, тй праект выводзіцца першым (20, 19, 18, 17)
