### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Цвет фона (прозрачная плажка меню) не соответствует ТЗ

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#13]
Вложение: https://monosnap.com/file/UQRueBWQeDBkvTcu8lEYOEUvacKXQ6
Ожидаемый результат: цвет фона (прозрачная плажка меню): цвет фона 1f1f1f, прозрачность 90% (согласно ТЗ)

**Comment by Omeljusik** [comment]
@Nika987 Неверна напісана назва бага. Калі мы пішым назву, то як мага менш пішам, што чагосьці няма, бо гэта ніяк не апісвае існуючую праблему, за выключэннем сітуацыі, калі па ТЗ напрыклад есць кнопка "Залагінецца", а яе няма.

У дадзеным выпадку ў загалоўке можна запісаць без дыталій, што колер празрыстага меню не адпавядае ТЗ, альбо написаць якія колер і празрыстасць зараз, а ўжо ўнутры, які павінен быць.

**Comment by Nika987** [comment]
@Omeljusik 
Дзякуй! Празрыстаць я змяніла, калі правярала, зараз не магу ужо напісаць як было. Шрыфт колера зараз #1D1C1C

**Comment by Omeljusik** [comment]
Усё добра.
