### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Порядок пунктов меню в футере не соответствует макету сайта

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#15]
Вложение: https://monosnap.com/file/VSq6811YimuohjGSbygqktPF5rwpqc 
Ожидаемый результат: пункты меню расположены в порядке, согласно макету
https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/main%20desktop.psd

**Comment by ossset** [comment]
Изменение будет сделано на серверной части, для повторного теста потребуется обновить базу данных.

**Comment by Nika987** [comment]
@ossset @Omeljusik 
Исправлено
