### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Отсутствует увеличение шрифта до 20 рх при наведении, отсутствует цвет шрифта ff6600 при нажатии в пунктах меню футера

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#16]
Вложение: https://monosnap.com/file/VSq6811YimuohjGSbygqktPF5rwpqc
Ожидаемый результат: согласно требованиям ТЗ пункты меню в футере: “Правілы сайта”, “FAQ”, “Зрабі ўнесак”, “Кантакты” -  имеют при наведении шрифт 20px, при нажатии цвет # ff6600.

**Comment by Nika987** [comment]
@ossset @Omeljusik 
не исправлено

**Comment by Omeljusik** [comment]
Гатова
