### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Отсутствует тень при наведении на значки соц. сетей в футере

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#17]
Вложение: https://monosnap.com/file/CvxWBZyPQFMc4OxVIROsuljtS92kzR
Ожидаемый результат: согласно требованиям ТЗ значки соц. сетей при наведении имеют небольшую тень, при нажатии - тень пропадает.

**Comment by ossset** [comment]
У задачи низший приоритет.
