### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Появляются рамки вокруг пунктов меню, значков соц. сетей, кнопок, расположенных в футере, при нажатии на них

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#18]
Вложение: https://monosnap.com/file/CvxWBZyPQFMc4OxVIROsuljtS92kzR
Ожидаемый результат: отсутствуют рамки вокруг пунктов меню, значков соц. сетей, кнопок, расположенных в футере, при нажатии на них.

**Comment by ossset** [comment]
Проявляется только в Firefox.

**Comment by Nika987** [comment]
@ossset так я и указала, что в браузере [Главная страница. Десктоп. Firefox]

**Comment by Omeljusik** [comment]
@Nika987 Ці правяраеш у хроме?

**Comment by Nika987** [comment]
Да, хроме такiх рамак няма
