### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Размер шрифта - 1.5em (24 рх) Стань валанцерам! не соответствует требованиям ТЗ

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#23]
Вложение: https://monosnap.com/file/3wgtezvy3HN39JGbEyQSVHIhP9Y4hW 
Ожидаемый результат: согласно требованиям ТЗ Блок 4. Стань валанцерам, 
Стань валанцерам! - 48 px

**Comment by ossset** [comment]
Не корректная задача - em это относительная величина токорая зависит от общей спецификации размера шрифта в body. Нужно протестировать блок с помощью pixel perfect  и потом подбирать шрифт(при необходимости).

**Comment by Nika987** [comment]
@ossset @Omeljusik 
В нач проекта мы было сказано, что лучше не использовать что-то вроде pixel perfect. Поэтому в данном случае, мне кажется, некорректно использовать относительную величину, которая зависит от общей специфики размера шрифта в боди, чтобы легче было понимать друг друга. Учесть, что в данном блоке только одно предложение, смею предположить, что шрифт непосредственно относится к фразе Стань валанцерам!
При помощи конвертера https://take.ms/I0kFh . Можно увидеть результат.

**Comment by Omeljusik** [comment]
Выглядае карэктга. Зачыняю.
