### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Отсутствует фоновый стиль, т.е.  полоски и кружочки, в блоке Гарачыя праекты.

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#24]
Вложение: https://monosnap.com/file/uunovkzwnnAqn6wHd2VShBFt2RrrKo 
Ожидаемый результат: фоновый стиль, согласно макету 
https://raw.githubusercontent.com/nastyafrosty/Falanster_new_website/master/Main%20page/%D0%A4%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D1%82%D1%8D%D1%80%20%D0%B3%D0%B0%D0%BB%D0%BE%D1%9E%D0%BD%D0%B0%D1%8F.png

**Comment by Nika987** [comment]
@ossset 
не исправлено

**Comment by Omeljusik** [comment]
Гатова.
