### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Блок Каляндар размещен после блока Блог

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#25]
Вложение: https://monosnap.com/file/LxlZiwDMoFZmffCYFCFAsmJiFpr6iW 
Ожидаемый результат: блок Каляндар размещен после блока Гарачыя праекты, согласно макету сайта
https://raw.githubusercontent.com/nastyafrosty/Falanster_new_website/master/Main%20page/%D0%A4%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D1%82%D1%8D%D1%80%20%D0%B3%D0%B0%D0%BB%D0%BE%D1%9E%D0%BD%D0%B0%D1%8F.png

**Comment by ossset** [comment]
@Omeljusik является ли задача критичной?

**Comment by Nika987** [comment]
@ossset 
Не исправлено
