### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Тень календаря имеет цвет d2ff1b

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#27]
Вложение: https://monosnap.com/file/FxYzSaD0g0jlxpfYAibOytxFOOCfMg
Ожидаемый результат: тень календаря имеет  цвет #d6ff32, согласно ТЗ
https://trello.com/c/xpci1rtc/88-1-%D0%B7%D1%80%D0%B0%D0%B1%D1%96%D1%86%D1%8C-%D0%BA%D0%B0%D0%BB%D1%8F%D0%BD%D0%B4%D0%B0%D1%80-%D0%B4%D0%BB%D1%8F-%D0%B3%D0%B0%D0%BB%D0%BE%D1%9E%D0%BD%D0%B0%D0%B9-%D1%83-%D0%BC%D0%B0%D0%BA%D1%81%D1%96%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D0%B9-%D0%B0%D0%B4%D0%BF%D0%B0%D0%B2%D0%B5%D0%B4%D0%BD%D0%B0%D1%81%D1%86%D1%96-%D0%B7-%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D0%B0%D0%BC

**Comment by koverchik** [comment]
Цвет изменен через модуль.

**Comment by Nika987** [comment]
@koverchik 
не исправлено
https://take.ms/pzRPj

**Comment by Omeljusik** [comment]
@koverchik гатова, дзякуй!
