### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Лишние пробелы в тексте календаря

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#28]
Вложение: https://monosnap.com/file/TJGyIYTWsVu8QVUShI3SQIKUEftpWw
Ожидаемый результат: 
                                      Пачатак: 18:00
                                      Заканчэнне: 20:00

**Comment by koverchik** [comment]
Поправлено.

**Comment by Nika987** [comment]
@koverchik 
не исправлено

https://take.ms/vE1f0
