### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Некорректно указано время Заканчэнне: 19.00

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#29]
Вложение: https://monosnap.com/file/iuIYBw4Tn03268ezYgLwx7cEER44Mk 
                   https://monosnap.com/file/MOtkVnIOO8chl7G6dBLZ77uQnXQuHo
Ожидаемый результат: 
"Як правіла з
18 да 20 адбываецца сустрэча
з 20 ++ адбываецца сазвонка."

Если вдуматься:
Пачатак: 18:00
Заканчэнне: 19:00 
Но согласно тексту, время встречи с 18 до 20.. Дальше с 20 ++ созвонка.... Я думаю, корректнее будет изменить время Заканчэнне на 20:00 или 21:00

**Comment by Omeljusik** [comment]
гэта пішуць самастойна ў апісанні пры стварэнні івэнта ў гугл-каляндарэ. Кантэнт будзе заўседы розны і не залежыць ад нашага модуля.

**Comment by Nika987** [comment]
@Omeljusik 
Дзякуй! Мы яшчэ у сб с гэтым разабралicя)
