### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Нет отступа между названием блока Календарь и событиями календаря

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#30]
Вложение: https://monosnap.com/file/YkjwJpK5OI5RBgLiTh5jfXIrs6D7V5
Ожидаемый результат: согласно макету есть отступ между названием блока Календарь и событиями календаря
https://trello-attachments.s3.amazonaws.com/5aaac9aa747059dc571ecd1e/5bc08b8f40831e1624574b6c/51e6f19662cbe11401732a4343bea8d7/image.png

**Comment by koverchik** [comment]
Требований к отступу не было поставила 30 px

**Comment by Nika987** [comment]
@koverchik 
не исправлено
https://take.ms/MonwV

**Comment by Omeljusik** [comment]
+1, выправлена
