### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Нет полосочек слева от края над блоком Календарь

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#31]
Вложение: https://monosnap.com/file/wklmogogPwN7w1ubgiKmMgbhnBjduG 
Ожидаемый результат: есть полосочки слева от края над блоком Календарь, согласно макету
https://trello-attachments.s3.amazonaws.com/5aaac9aa747059dc571ecd1e/5bc08b8f40831e1624574b6c/51e6f19662cbe11401732a4343bea8d7/image.png

**Comment by Nika987** [comment]
@ossset 
не исправлено

**Comment by Omeljusik** [comment]
@ossset palosak njama. Treba dadat.

![image](https://user-images.githubusercontent.com/32821205/56096276-ca411100-5eee-11e9-8c05-5c8385d268a6.png)
