### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Текст события календаря увеличивается

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#32]
Вложение: https://monosnap.com/file/jIoUzsALJVAzzRIZLUvl0OMd6HyOUP
https://monosnap.com/file/4m7By0fdUqPmJQs1B3EiFXyCGtKvg8
Ожидаемый результат: текст равномерный 
P.S. шрифт текста 16 px указан верно, но почему-то он не равномерный по сравнению с другими строками

**Comment by koverchik** [comment]
Проблема была не с размером шрифта, а с начертанием.  Поставила 'Ubuntu' на теги "a".

**Comment by Omeljusik** [comment]
зроблена.
