### ISSUE TITLE
[Гл. страница. Десктоп. Firefox] Футер. Поле для ввода эл. адреса принимает невалидные значения имени электронного адреса, в частности знаки и спецсимволы

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#33]
Вложение: https://monosnap.com/file/ZcnOCzFUuAOtnyKrE9oXcJSAEPfRgS 
Ожидаемый результат: поля для ввода эл. адреса принимает только допустимые значения, которые соответствуют корректному имени электронного адреса: допустимо использовать только латинские буквы, цифры, знак подчеркивания («_»), точку («.»), минус («-»)

**Comment by Omeljusik** [comment]
гэта верна рэалізавана ў верстке https://diglabby.github.io/Falanster-site/

**Comment by Nika987** [comment]
@Omeljusik @koverchik 
не исправлено

**Comment by Omeljusik** [comment]
08.10 усе ок
