### ISSUE TITLE
[Гл. страница. Десктоп. Firefox| Chrome] Осуществляется переход в начало страницы по заголовкам проекта в блоке Гарачыя праекты

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#34]
Вложение: https://take.ms/pKeud
Ожидаемый результат: заголовки проектов не кликабельны.

**Comment by ossset** [comment]
Эта ішью не вельмі добрая, бо мы яшчэ не рабілі унатраную таму кнопкі не працуюць.

**Comment by Nika987** [comment]
@ossset 
А что на твой взгляд добрая или плохая?)

**Comment by Nika987** [comment]
@ossset 
Переход по всем заголовкам осуществляется.

**Comment by Omeljusik** [comment]
зачыняю, бо пакуль рана тэставаць гэту функцыянальнасць.

зараз пераход на вікіфікацыю, але гэта проста заглушка, як разумею. @ossset
