### ISSUE TITLE
[Гл. страница. Десктоп. Firefox| Chrome] Цвет шрифта заголовков проекта не соответствует требованиям ТЗ в блоке Гарачыя праекты

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#35]
Вложение: https://take.ms/yZSmw
Ожидаемый результат: цвет шрифта заголовков #333333

**Comment by ossset** [comment]
Done

**Comment by Nika987** [comment]
@ossset @Omeljusik 
Ребята, мне кажется, для понимания друг друга. Давайте соблюдать требования ТЗ. Если в ТЗ указан шрифт #333333 Значит, этот шрифт и должен быть в верстке сайта. На данный момент шрифт #lalala
https://take.ms/YyffL

**Comment by Omeljusik** [comment]
@ossset Тут ТЗ https://docs.google.com/document/d/11vrJMGsbj9pUZvviJvD_RbJlmZrumwtCvAWlaYlOwK0/edit#

#333333 - павінен быць у загалоўкаў (таго, што бачны адразу і пры навдзенні)

**Comment by Omeljusik** [comment]
@ossset Тут зроблена,
дзякуй!
