### ISSUE TITLE
[Гл. страница. Десктоп. Firefox| Chrome] Цвет шрифта текста #767676 в блоке Гарачыя праекты

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#37]
Вложение: https://take.ms/KNGKo 
Ожидаемый результат: #333333

**Comment by ossset** [comment]
Калі ласка праглдзце яшчэ раз гэты ішью @Nika987 #333333 гэта не той колер.

**Comment by ossset** [comment]
Калі ласка удакладні ішью @Nika987

**Comment by Omeljusik** [comment]
@ossset Тут ТЗ https://docs.google.com/document/d/11vrJMGsbj9pUZvviJvD_RbJlmZrumwtCvAWlaYlOwK0/edit#

#333333 - павінен быць у загалоўкаў (таго, што бачны адразу і пры навдзенні). #35

Тэкст #767676 верна. Гэту іш'ю зачыняю, але колерр загалоўкаў правіць трэба.
