### ISSUE TITLE
[Гл. страница. Десктоп. Firefox| Chrome] Отсутствует полупрозрачность на проекты при наведении курсора в блоке Гарачыя праекты 

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#38]
Сейчас так:  https://take.ms/44SYz 

Надо, чтобы было так: https://take.ms/9GAjl

**Comment by Nika987** [comment]
@ossset 
Не исправлено

**Comment by Omeljusik** [comment]
не магу пратэсціраваць на лакале, бо няма малюнкаў - не бачна. Але бачыла ў @ossset што працуе, таму зачыняю.
