### ISSUE TITLE
[Гл. страница. Десктоп. Firefox| Chrome] Последние статьи Блога выводятся один под одним вместо того, чтобы отображаться справа.

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#41]
Вложение: https://monosnap.com/file/3Vs7UkCpECpwA25kA1CH9sXm4TvE7i
Ожидаемый результат: заголовки текста размещены слева и справа в блоке Блок, согласно макету.
Прилагается макет: https://raw.githubusercontent.com/nastyafrosty/Falanster_new_website/master/Main%20page/%D0%A4%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D1%82%D1%8D%D1%80%20%D0%B3%D0%B0%D0%BB%D0%BE%D1%9E%D0%BD%D0%B0%D1%8F.png

**Comment by Omeljusik** [comment]
@Nika987 забыла ўкладанне.

**Comment by ossset** [comment]
Трэба удакладненне @Nika987

**Comment by Nika987** [comment]
@ossset @Omeljusik 
Обратите внимание на макет)
Скрин, как на макете https://take.ms/ctaU3 - на сайте должно быть так же.

**Comment by Omeljusik** [comment]
ок
