### ISSUE TITLE
[Гл. страница. Десктоп. Firefox| Chrome] Отсутствует ссылка Усе падзеі в блоке Блог

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#42]
Вложение: https://take.ms/xAKdz
Ожидаемый результат: размещается ссылка Усе падзеі справа под заголовками текста в конце блока Блог, согласно макету
Прилагается макет: https://raw.githubusercontent.com/nastyafrosty/Falanster_new_website/master/Main%20page/%D0%A4%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D1%82%D1%8D%D1%80%20%D0%B3%D0%B0%D0%BB%D0%BE%D1%9E%D0%BD%D0%B0%D1%8F.png

**Comment by Nika987** [comment]
@ossset 
Во вложении ответ на твой вопрос https://take.ms/3cTtM .

**Comment by Omeljusik** [comment]
![image](https://user-images.githubusercontent.com/32821205/56095917-2fdece80-5eea-11e9-9864-1ebec75d366a.png)

Для прагляда https://diglabby.github.io/Falanster-site/
