### ISSUE TITLE
[Главная страница. Десктоп. Firefox] Обновить фавикон на новый 

### ISSUE THREAD

**Issue by Nika987** [falanster/devfalanster#8]
Вложение: https://monosnap.com/file/9UDYHIslq2dK1QH0EKDO5d29FxeZqm
Ожидаемый результат: фавикон обновлен

**Comment by ossset** [comment]
Зрабіў пр, тэсцім.

**Comment by Omeljusik** [comment]
@ossset фавікон увогуле не падгружаецца

**Comment by Omeljusik** [comment]
ёсць на фтэст.
