### ISSUE TITLE
[Organization] Немагчыма дадаць фонавы малюнак і прев'ю з-за памылак

### ISSUE THREAD

**Issue by Omeljusik** [falanster/devfalanster#81]
![image](https://user-images.githubusercontent.com/32821205/61459718-082e5500-a976-11e9-9df6-25bd8fb5c562.png)

Чтобы воспроизвести, попробовать загрузить картинки https://ftest.falanster.by/ru/node/add/organization

**Comment by koverchik** [comment]
@Omeljusik  у меня сохранилась https://ftest.falanster.by/ru/node/add/organization

**Comment by Omeljusik** [comment]
@koverchik так, выбач, усё ок https://ftest.falanster.by/ru/node/1174
