### ISSUE TITLE
[Адмінка] Знікае адмін панэль пасля першага націску на адну з опцый.

### ISSUE THREAD

**Issue by Omeljusik** [falanster/devfalanster#89]
## Праяўляецца пастаянна. І не магчыма выйсці з адмінкі.

![image](https://user-images.githubusercontent.com/32821205/61469643-3f0d6680-a988-11e9-87cf-15f9820351b6.png)

**Comment by koverchik** [comment]
Ресурсов и желания анализировать исправлять данный баг у меня нет. @Omeljusik  назначь кого-нибудь другого решать данную ошибку.

**Comment by Omeljusik** [comment]
Хутчэй за ўсё пачысцілі кэш на сервере і ўсё запрацавала.
