### ISSUE TITLE
[Унутраная] Не бачна спасылак у тэксце. Павінны быць падкрэсленыя.

### ISSUE THREAD

**Issue by Omeljusik** [falanster/devfalanster#91]
Як зараз: https://ftest.falanster.by/ru/bootcamp2 Глядзець спасылку ў Важная інфармацыя. Яна выглядае як звычайны тэкст, пры навядзенні робіцца памаранчывай.

Як павінна быць - глядзець тут https://diglabby.github.io/Falanster-site/event 
Спасылкі падкрэсленыя, пры навядзенні памаранчывыя, пры націску знікае падкрэсліванне.

**Comment by koverchik** [comment]
@Omeljusik пиши задачу с четким описание как должно выглядеть

**Comment by Omeljusik** [comment]
@koverchik "Спасылкі падкрэсленыя, пры навядзенні памаранчывыя, пры націску знікае падкрэсліванне" 
і дала спасылку на прыклад. 
Гэтага не дастаткова?

**Comment by koverchik** [comment]
@Omeljusik нет. 
Четкое описание. 
Пример:
Ссылки расположенные в основном тексте на внутренних страницах должны быть выделены жирным шрифтом и отображаться в цвете #333333, размер шрифта 16px, начертание шрифта "PT Sans". При наведении на ссылку меняется цвет на #bebebe и появляется подчеркивание, размер шрифта не меняется.

**Comment by Omeljusik** [comment]
Спасылкі падкрэсленыя, пры навядзенні памаранчывыя, пры націску знікае падкрэсліванне.
колер пры навядзении и нациску - #ff6600

**Comment by koverchik** [comment]
https://github.com/falanster/devfalanster/blob/5a2e93a30ff4a7a5bed04ca74fa4901b61f48d61/sites/all/themes/new_falanster/css/style.css#L2
Деректива "!important;" в свойстве "text-decoration: none !important;" создает ошибку в стиле. Тег <a> используется повсеместно во всем проекте. Изменение данного свойства влияет на все теги. За принятия решение изменения директивы "!important" я не берусь. @Omeljusik

**Comment by Omeljusik** [comment]
Так, калі гэта дапамагае, давай паспрабуем.

**Comment by Omeljusik** [comment]
на 10.08.19 на тэсце ўс1 ок, прыбралі important утчэй за ўсё
